// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class AddStudentResult
    {
        public int? StudentId { get; set; }
        [StringLength(28)]
        public string Message { get; set; }
    }
}
