// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class AssignInstructorToCourseResult
    {
        [StringLength(42)]
        public string Message { get; set; }
        public int? InstructorID { get; set; }
        public int? CourseID { get; set; }
    }
}
