// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("branch")]
public partial class branch
{
    [Key]
    public int branch_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string branch_name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string branch_city { get; set; }

    [InverseProperty("branch")]
    public virtual ICollection<person_jong_department_branch> person_jong_department_branches { get; set; } = new List<person_jong_department_branch>();

    [ForeignKey("branch_id")]
    [InverseProperty("branches")]
    public virtual ICollection<department> departments { get; set; } = new List<department>();
}