// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class CorrectExamResult
    {
        public int? exam_id { get; set; }
        public int? student_id { get; set; }
        public int? total_questions { get; set; }
        public int? correct_answers { get; set; }
        [Column("final_score", TypeName = "decimal(5,2)")]
        public decimal? final_score { get; set; }
    }
}
