// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("course_id", "question_id", "topic_id")]
[Table("course_questions_on_topic")]
public partial class course_questions_on_topic
{
    [Key]
    public int course_id { get; set; }

    [Key]
    public int question_id { get; set; }

    [Key]
    public int topic_id { get; set; }

    [ForeignKey("course_id")]
    [InverseProperty("course_questions_on_topics")]
    public virtual course course { get; set; }

    [ForeignKey("question_id")]
    [InverseProperty("course_questions_on_topics")]
    public virtual question question { get; set; }

    [ForeignKey("topic_id")]
    [InverseProperty("course_questions_on_topics")]
    public virtual topic topic { get; set; }
}