// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

public partial class db37500Context : DbContext
{
    public db37500Context()
    {
    }

    public db37500Context(DbContextOptions<db37500Context> options)
        : base(options)
    {
    }

    public virtual DbSet<branch> branches { get; set; }

    public virtual DbSet<course> courses { get; set; }

    public virtual DbSet<course_questions_on_topic> course_questions_on_topics { get; set; }

    public virtual DbSet<department> departments { get; set; }

    public virtual DbSet<exam> exams { get; set; }

    public virtual DbSet<instructor> instructors { get; set; }

    public virtual DbSet<instructor_generate_course_exam> instructor_generate_course_exams { get; set; }

    public virtual DbSet<person> people { get; set; }

    public virtual DbSet<person_jong_department_branch> person_jong_department_branches { get; set; }

    public virtual DbSet<quesiton_choice> quesiton_choices { get; set; }

    public virtual DbSet<question> questions { get; set; }

    public virtual DbSet<student> students { get; set; }

    public virtual DbSet<student_answer_question> student_answer_questions { get; set; }

    public virtual DbSet<student_course> student_courses { get; set; }

    public virtual DbSet<student_exam> student_exams { get; set; }

    public virtual DbSet<topic> topics { get; set; }

    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<branch>(entity =>
        {
            entity.HasKey(e => e.branch_id).HasName("PK__branch__E55E37DEA9213C67");

            entity.HasMany(d => d.departments).WithMany(p => p.branches)
                .UsingEntity<Dictionary<string, object>>(
                    "branch_department",
                    r => r.HasOne<department>().WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__branch_de__depar__6383C8BA"),
                    l => l.HasOne<branch>().WithMany()
                        .HasForeignKey("branch_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__branch_de__branc__628FA481"),
                    j =>
                    {
                        j.HasKey("branch_id", "department_id").HasName("PK__branch_d__D97C059C28D43EFC");
                        j.ToTable("branch_department");
                    });
        });

        modelBuilder.Entity<course>(entity =>
        {
            entity.HasKey(e => e.course_id).HasName("PK__courses__8F1EF7AE48E41533");

            entity.HasMany(d => d.departments).WithMany(p => p.courses)
                .UsingEntity<Dictionary<string, object>>(
                    "department_course",
                    r => r.HasOne<department>().WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__departmen__depar__656C112C"),
                    l => l.HasOne<course>().WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__departmen__cours__6477ECF3"),
                    j =>
                    {
                        j.HasKey("course_id", "department_id").HasName("PK__departme__B33CC5ECEB565F7F");
                        j.ToTable("department_courses");
                    });
        });

        modelBuilder.Entity<course_questions_on_topic>(entity =>
        {
            entity.HasKey(e => new { e.course_id, e.question_id, e.topic_id }).HasName("PK__course_q__E5270C59ECF3EE89");

            entity.HasOne(d => d.course).WithMany(p => p.course_questions_on_topics)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__course_qu__cours__787EE5A0");

            entity.HasOne(d => d.question).WithMany(p => p.course_questions_on_topics)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__course_qu__quest__797309D9");

            entity.HasOne(d => d.topic).WithMany(p => p.course_questions_on_topics)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__course_qu__topic__7A672E12");
        });

        modelBuilder.Entity<department>(entity =>
        {
            entity.HasKey(e => e.department_id).HasName("PK__departme__C2232422F8B79851");
        });

        modelBuilder.Entity<exam>(entity =>
        {
            entity.HasKey(e => e.exam_id).HasName("PK__exam__9C8C7BE92266F27C");

            entity.HasMany(d => d.questoins).WithMany(p => p.exams)
                .UsingEntity<Dictionary<string, object>>(
                    "exam_question",
                    r => r.HasOne<question>().WithMany()
                        .HasForeignKey("questoin_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__exam_ques__quest__68487DD7"),
                    l => l.HasOne<exam>().WithMany()
                        .HasForeignKey("exam_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__exam_ques__exam___6754599E"),
                    j =>
                    {
                        j.HasKey("exam_id", "questoin_id").HasName("PK__exam_que__E8EC932AA59D9F32");
                        j.ToTable("exam_questions");
                    });
        });

        modelBuilder.Entity<instructor>(entity =>
        {
            entity.HasKey(e => e.instructor_id).HasName("PK__instruct__A1EF56E81576EB83");

            entity.Property(e => e.instructor_id).ValueGeneratedNever();

            entity.HasOne(d => d.instructorNavigation).WithOne(p => p.instructor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__instructo__instr__6C190EBB");

            entity.HasMany(d => d.courses).WithMany(p => p.instructors)
                .UsingEntity<Dictionary<string, object>>(
                    "instructor_course",
                    r => r.HasOne<course>().WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__instructo__cours__71D1E811"),
                    l => l.HasOne<instructor>().WithMany()
                        .HasForeignKey("instructor_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__instructo__instr__70DDC3D8"),
                    j =>
                    {
                        j.HasKey("instructor_id", "course_id").HasName("PK__instruct__591EB992CE4C8B67");
                        j.ToTable("instructor_course");
                    });
        });

        modelBuilder.Entity<instructor_generate_course_exam>(entity =>
        {
            entity.HasKey(e => new { e.instructor_id, e.course_id, e.genrate_date }).HasName("PK__instruct__0961CD79737882FE");

            entity.HasOne(d => d.course).WithMany(p => p.instructor_generate_course_exams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__instructo__cours__778AC167");

            entity.HasOne(d => d.exam).WithMany(p => p.instructor_generate_course_exams).HasConstraintName("FK__instructo__exam___76969D2E");

            entity.HasOne(d => d.instructor).WithMany(p => p.instructor_generate_course_exams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__instructo__instr__75A278F5");
        });

        modelBuilder.Entity<person>(entity =>
        {
            entity.HasKey(e => e.person_id).HasName("PK__person__543848DFE0E68079");
        });

        modelBuilder.Entity<person_jong_department_branch>(entity =>
        {
            entity.HasKey(e => new { e.person_id, e.join_date }).HasName("PK__person_j__F2DF8C675A4F82B8");

            entity.HasOne(d => d.branch).WithMany(p => p.person_jong_department_branches).HasConstraintName("FK__person_jo__branc__73BA3083");

            entity.HasOne(d => d.department).WithMany(p => p.person_jong_department_branches).HasConstraintName("FK__person_jo__depar__74AE54BC");

            entity.HasOne(d => d.person).WithMany(p => p.person_jong_department_branches)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__person_jo__perso__72C60C4A");
        });

        modelBuilder.Entity<quesiton_choice>(entity =>
        {
            entity.HasKey(e => e.choice_id).HasName("PK__quesiton__33CAF83A7B201092");
        });

        modelBuilder.Entity<question>(entity =>
        {
            entity.HasKey(e => e.question_id).HasName("PK__question__2EC21549A9B6A554");

            entity.HasOne(d => d.correct_ans).WithMany(p => p.questions).HasConstraintName("FK__question__correc__66603565");

            entity.HasMany(d => d.choices).WithMany(p => p.questionsNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "question_choise_bridge",
                    r => r.HasOne<quesiton_choice>().WithMany()
                        .HasForeignKey("choice_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__question___choic__6A30C649"),
                    l => l.HasOne<question>().WithMany()
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__question___quest__693CA210"),
                    j =>
                    {
                        j.HasKey("question_id", "choice_id").HasName("PK__question__9DFEBACAF97394DE");
                        j.ToTable("question_choise_bridge");
                    });
        });

        modelBuilder.Entity<student>(entity =>
        {
            entity.HasKey(e => e.student_id).HasName("PK__student__2A33069A73ADE165");

            entity.Property(e => e.student_id).ValueGeneratedNever();

            entity.HasOne(d => d.studentNavigation).WithOne(p => p.student)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student__student__6B24EA82");
        });

        modelBuilder.Entity<student_answer_question>(entity =>
        {
            entity.HasKey(e => new { e.student_id, e.quesiotn_id, e.answer_date }).HasName("PK__student___06872EC7F17FD9FC");

            entity.HasOne(d => d.exam).WithMany(p => p.student_answer_questions).HasConstraintName("FK__student_a__exam___7C4F7684");

            entity.HasOne(d => d.quesiotn).WithMany(p => p.student_answer_questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_a__quesi__7D439ABD");

            entity.HasOne(d => d.student).WithMany(p => p.student_answer_questions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_a__stude__7B5B524B");
        });

        modelBuilder.Entity<student_course>(entity =>
        {
            entity.HasKey(e => new { e.student_id, e.course_id }).HasName("PK__student___D2C2E9E0EC42EC12");

            entity.HasOne(d => d.course).WithMany(p => p.student_courses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_c__cours__6FE99F9F");

            entity.HasOne(d => d.student).WithMany(p => p.student_courses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_c__stude__6EF57B66");
        });

        modelBuilder.Entity<student_exam>(entity =>
        {
            entity.HasKey(e => new { e.student_id, e.exam_id }).HasName("PK__student___A3FBC1247196A2E6");

            entity.HasOne(d => d.exam).WithMany(p => p.student_exams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_e__exam___6E01572D");

            entity.HasOne(d => d.student).WithMany(p => p.student_exams)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_e__stude__6D0D32F4");
        });

        modelBuilder.Entity<topic>(entity =>
        {
            entity.HasKey(e => e.topic_id).HasName("PK__topic__D5DAA3E9299693CA");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}