// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class DeleteExamResult
    {
        [StringLength(25)]
        public string Message { get; set; }
        public int? DeletedExamID { get; set; }
    }
}
