// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("department")]
public partial class department
{
    [Key]
    public int department_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string department_name { get; set; }

    [InverseProperty("department")]
    public virtual ICollection<person_jong_department_branch> person_jong_department_branches { get; set; } = new List<person_jong_department_branch>();

    [ForeignKey("department_id")]
    [InverseProperty("departments")]
    public virtual ICollection<branch> branches { get; set; } = new List<branch>();

    [ForeignKey("department_id")]
    [InverseProperty("departments")]
    public virtual ICollection<course> courses { get; set; } = new List<course>();
}