// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("exam")]
public partial class exam
{
    [Key]
    public int exam_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string exam_title { get; set; }

    public int? total_grade { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? exam_date { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string exam_type { get; set; }

    public int? duration_mins { get; set; }

    [InverseProperty("exam")]
    public virtual ICollection<instructor_generate_course_exam> instructor_generate_course_exams { get; set; } = new List<instructor_generate_course_exam>();

    [InverseProperty("exam")]
    public virtual ICollection<student_answer_question> student_answer_questions { get; set; } = new List<student_answer_question>();

    [InverseProperty("exam")]
    public virtual ICollection<student_exam> student_exams { get; set; } = new List<student_exam>();

    [ForeignKey("exam_id")]
    [InverseProperty("exams")]
    public virtual ICollection<question> questoins { get; set; } = new List<question>();
}