// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetAllQuestionsWithChoicesPivotedResult
    {
        public int QuestionID { get; set; }
        [StringLength(255)]
        public string QuestionText { get; set; }
        [StringLength(50)]
        public string QuestionType { get; set; }
        [StringLength(50)]
        public string Difficulty { get; set; }
        public int? CorrectAnswerID { get; set; }
        public int? Choice1_ID { get; set; }
        [StringLength(255)]
        public string Choice1_Text { get; set; }
        public int? Choice2_ID { get; set; }
        [StringLength(255)]
        public string Choice2_Text { get; set; }
        public int? Choice3_ID { get; set; }
        [StringLength(255)]
        public string Choice3_Text { get; set; }
        public int? Choice4_ID { get; set; }
        [StringLength(255)]
        public string Choice4_Text { get; set; }
    }
}
