// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetBranchByIdResult
    {
        [Column("Branch Name")]
        [StringLength(255)]
        public string BranchName { get; set; }
        [Column("Branch City")]
        [StringLength(255)]
        public string BranchCity { get; set; }
    }
}
