// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetCourseTopicsResult
    {
        public int CourseID { get; set; }
        [StringLength(255)]
        public string CourseTitle { get; set; }
        public int? CourseCode { get; set; }
        [StringLength(255)]
        public string CourseDescription { get; set; }
        [StringLength(255)]
        public string Credits { get; set; }
        public int TopicID { get; set; }
        [StringLength(255)]
        public string TopicTitle { get; set; }
        public int? TopicOrder { get; set; }
        [StringLength(255)]
        public string TopicDuration { get; set; }
        public int? TotalTopics { get; set; }
        [StringLength(34)]
        public string TopicProgress { get; set; }
    }
}
