// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetDepartmentCoursesResult
    {
        public int course_id { get; set; }
        public int? course_code { get; set; }
        [StringLength(255)]
        public string course_title { get; set; }
        [StringLength(255)]
        public string description { get; set; }
        [StringLength(255)]
        public string credits { get; set; }
    }
}
