// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetExamByIdResult
    {
        public int exam_id { get; set; }
        [StringLength(255)]
        public string exam_title { get; set; }
        public int? total_grade { get; set; }
        public DateTime? exam_date { get; set; }
        [StringLength(50)]
        public string exam_type { get; set; }
        public int? duration_mins { get; set; }
        public int? course_id { get; set; }
        [StringLength(255)]
        public string course_title { get; set; }
        public int? instructor_id { get; set; }
        [StringLength(511)]
        public string instructor_name { get; set; }
    }
}
