// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetExamQuestionsResult
    {
        public int question_id { get; set; }
        [StringLength(255)]
        public string question_text { get; set; }
        [StringLength(50)]
        public string question_type { get; set; }
        [StringLength(50)]
        public string question_difficulty { get; set; }
        public int? choice_id { get; set; }
        [StringLength(255)]
        public string choice_text { get; set; }
        public int is_correct { get; set; }
    }
}
