// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetInstructorByIdResult
    {
        public int instructor_id { get; set; }
        [StringLength(255)]
        public string first_name { get; set; }
        [StringLength(255)]
        public string last_name { get; set; }
        [StringLength(255)]
        public string email { get; set; }
        public DateOnly? hire_date { get; set; }
    }
}
