// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class GetTopicByIdResult
    {
        public int topic_id { get; set; }
        public int? topic_order { get; set; }
        [StringLength(255)]
        public string topic_duration { get; set; }
        [StringLength(255)]
        public string topic_title { get; set; }
    }
}
