// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Examination_system.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Examination_system.Models
{
    public partial interface Idb37500ContextProcedures
    {
        Task<List<AddBranchResult>> AddBranchAsync(string name, string city, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddCourseAsync(int? course_code, string description, string course_title, string credits, OutputParameter<int?> course_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AddCourseToDepartmentResult>> AddCourseToDepartmentAsync(int? courseID, int? departmentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AddDepartmentResult>> AddDepartmentAsync(string name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AddDepartmentToBranchResult>> AddDepartmentToBranchAsync(int? branch_id, int? department_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AddInstructorResult>> AddInstructorAsync(string firstName, string lastName, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AddStudentResult>> AddStudentAsync(string firstName, string lastName, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddTopicAsync(int? topic_order, string topic_duration, string topic_title, OutputParameter<int?> topic_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AssignInstructorToCourseResult>> AssignInstructorToCourseAsync(int? instructorID, int? courseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<CorrectExamResult>> CorrectExamAsync(int? exam_id, int? student_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeleteBranchResult>> DeleteBranchAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteChoiceAsync(int? choiceID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteCourseAsync(int? course_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteDepartmentAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeleteExamResult>> DeleteExamAsync(int? examID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeleteInstructorResult>> DeleteInstructorAsync(int? instructorId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteQuestionAsync(int? questionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DeleteStudentResult>> DeleteStudentAsync(int? studentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteTopicAsync(int? topic_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<EnrollStudentInCourseResult>> EnrollStudentInCourseAsync(int? studentID, int? courseID, DateTime? enrollmentDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GenerateExamResult>> GenerateExamAsync(DataTable items, int? course_id, string exam_title, DateTime? exam_date, int? duration_mins, decimal? total_grade, int? instructor_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllExamsResult>> GetAllExamsAsync(int? courseID, string examType, int? instructorID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllInstructorsResult>> GetAllInstructorsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllQuestionsWithChoicesPivotedResult>> GetAllQuestionsWithChoicesPivotedAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllStudentsResult>> GetAllStudentsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetBranchByIdResult>> GetBranchByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetChoicesByQuestionIdResult>> GetChoicesByQuestionIdAsync(int? questionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetCourseByIdResult>> GetCourseByIdAsync(int? course_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetCourseTopicsResult>> GetCourseTopicsAsync(int? courseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDepartmentByIdResult>> GetDepartmentByIdAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDepartmentCoursesResult>> GetDepartmentCoursesAsync(int? departmentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetExamByIdResult>> GetExamByIdAsync(int? examID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetExamQuestionsResult>> GetExamQuestionsAsync(int? examID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetExamQuestionsWithChoicesPivotedResult>> GetExamQuestionsWithChoicesPivotedAsync(int? examID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetInstructorByIdResult>> GetInstructorByIdAsync(int? instructorId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetInstructorCoursesResult>> GetInstructorCoursesAsync(int? instructorID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetQuestionsForCourseTopicResult>> GetQuestionsForCourseTopicAsync(int? courseID, int? topicID, string questionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetQuestionWithChoicesResult>> GetQuestionWithChoicesAsync(int? questionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetQuestionWithChoicesPivotedResult>> GetQuestionWithChoicesPivotedAsync(int? questionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentByIdResult>> GetStudentByIdAsync(int? studentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentCoursesResult>> GetStudentCoursesAsync(int? studentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTopicByIdResult>> GetTopicByIdAsync(int? topic_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertMCQChoiceAsync(int? questionID, string choiceText, bool? isCorrect, OutputParameter<int?> newChoiceID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<InsertQuestionResult>> InsertQuestionAsync(string questionText, string questionType, string questionDifficulty, OutputParameter<int?> newQuestionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertTrueFalseChoicesAsync(int? questionID, bool? correctAnswer, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LinkQuestionToCourseTopicResult>> LinkQuestionToCourseTopicAsync(int? questionID, int? courseID, int? topicID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RemoveCourseFromDepartmentResult>> RemoveCourseFromDepartmentAsync(int? courseID, int? departmentID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RemoveInstructorFromCourseResult>> RemoveInstructorFromCourseAsync(int? instructorID, int? courseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetExamForStudentResult>> sp_GetExamForStudentAsync(int? student_id, int? exam_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<StudentSubmitAnswersResult>> StudentSubmitAnswersAsync(int? student_id, int? exam_id, DataTable answers, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UnenrollStudentFromCourseResult>> UnenrollStudentFromCourseAsync(int? studentID, int? courseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UnlinkQuestionFromCourseTopicResult>> UnlinkQuestionFromCourseTopicAsync(int? questionID, int? courseID, int? topicID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateBranchResult>> UpdateBranchAsync(int? id, string new_name, string new_city, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateChoiceTextAsync(int? choiceID, string choiceText, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateCourseAsync(int? course_id, int? course_code, string description, string course_title, string credits, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateDepartmentResult>> UpdateDepartmentAsync(int? id, string new_name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateExamResult>> UpdateExamAsync(int? examID, string examTitle, DateTime? examDate, string examType, int? durationMins, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateInstructorResult>> UpdateInstructorAsync(int? instructorId, string firstName, string lastName, string email, DateOnly? hireDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateQuestionAsync(int? questionID, string questionText, string questionDifficulty, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateQuestionCorrectAnswerAsync(int? questionID, int? newCorrectChoiceID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateStudentResult>> UpdateStudentAsync(int? studentId, string firstName, string lastName, string email, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateTopicAsync(int? topic_id, int? topic_order, string topic_duration, string topic_title, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
