// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class InsertQuestionResult
    {
        public int? QuestionID { get; set; }
        public int Success { get; set; }
        [StringLength(25)]
        public string Message { get; set; }
    }
}
