// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("instructor_id", "course_id", "genrate_date")]
[Table("instructor_generate_course_exam")]
public partial class instructor_generate_course_exam
{
    [Key]
    public int instructor_id { get; set; }

    public int? exam_id { get; set; }

    [Key]
    public int course_id { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime genrate_date { get; set; }

    [ForeignKey("course_id")]
    [InverseProperty("instructor_generate_course_exams")]
    public virtual course course { get; set; }

    [ForeignKey("exam_id")]
    [InverseProperty("instructor_generate_course_exams")]
    public virtual exam exam { get; set; }

    [ForeignKey("instructor_id")]
    [InverseProperty("instructor_generate_course_exams")]
    public virtual instructor instructor { get; set; }
}