// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("instructor")]
public partial class instructor
{
    [Key]
    public int instructor_id { get; set; }

    public DateOnly? hire_date { get; set; }

    [ForeignKey("instructor_id")]
    [InverseProperty("instructor")]
    public virtual person instructorNavigation { get; set; }

    [InverseProperty("instructor")]
    public virtual ICollection<instructor_generate_course_exam> instructor_generate_course_exams { get; set; } = new List<instructor_generate_course_exam>();

    [ForeignKey("instructor_id")]
    [InverseProperty("instructors")]
    public virtual ICollection<course> courses { get; set; } = new List<course>();
}