// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("person")]
public partial class person
{
    [Key]
    public int person_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string first_name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string last_name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string email { get; set; }

    [InverseProperty("instructorNavigation")]
    public virtual instructor instructor { get; set; }

    [InverseProperty("person")]
    public virtual ICollection<person_jong_department_branch> person_jong_department_branches { get; set; } = new List<person_jong_department_branch>();

    [InverseProperty("studentNavigation")]
    public virtual student student { get; set; }
}