// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("person_id", "join_date")]
[Table("person_jong_department_branch")]
public partial class person_jong_department_branch
{
    [Key]
    public int person_id { get; set; }

    public int? branch_id { get; set; }

    public int? department_id { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime join_date { get; set; }

    [ForeignKey("branch_id")]
    [InverseProperty("person_jong_department_branches")]
    public virtual branch branch { get; set; }

    [ForeignKey("department_id")]
    [InverseProperty("person_jong_department_branches")]
    public virtual department department { get; set; }

    [ForeignKey("person_id")]
    [InverseProperty("person_jong_department_branches")]
    public virtual person person { get; set; }
}