// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("quesiton_choice")]
public partial class quesiton_choice
{
    [Key]
    public int choice_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string choice_text { get; set; }

    [InverseProperty("correct_ans")]
    public virtual ICollection<question> questions { get; set; } = new List<question>();

    [ForeignKey("choice_id")]
    [InverseProperty("choices")]
    public virtual ICollection<question> questionsNavigation { get; set; } = new List<question>();
}