// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("question")]
public partial class question
{
    [Key]
    public int question_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string question_text { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string question_type { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string question_difficulty { get; set; }

    public int? correct_ans_id { get; set; }

    [ForeignKey("correct_ans_id")]
    [InverseProperty("questions")]
    public virtual quesiton_choice correct_ans { get; set; }

    [InverseProperty("question")]
    public virtual ICollection<course_questions_on_topic> course_questions_on_topics { get; set; } = new List<course_questions_on_topic>();

    [InverseProperty("quesiotn")]
    public virtual ICollection<student_answer_question> student_answer_questions { get; set; } = new List<student_answer_question>();

    [ForeignKey("question_id")]
    [InverseProperty("questionsNavigation")]
    public virtual ICollection<quesiton_choice> choices { get; set; } = new List<quesiton_choice>();

    [ForeignKey("questoin_id")]
    [InverseProperty("questoins")]
    public virtual ICollection<exam> exams { get; set; } = new List<exam>();
}