// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_system.Models
{
    public partial class sp_GetExamForStudentResult
    {
        public int ExamID { get; set; }
        [StringLength(255)]
        public string ExamTitle { get; set; }
        public int? TotalGrade { get; set; }
        public DateTime? ExamDate { get; set; }
        public int? DurationMinutes { get; set; }
        public int? StudentGrade { get; set; }
        [StringLength(255)]
        public string ExamState { get; set; }
        [StringLength(63)]
        public string ScoreDisplay { get; set; }
        public int QuestionID { get; set; }
        [StringLength(255)]
        public string QuestionText { get; set; }
        [StringLength(50)]
        public string QuestionType { get; set; }
        [StringLength(50)]
        public string Difficulty { get; set; }
        [StringLength(255)]
        public string StudentChoice { get; set; }
        [StringLength(255)]
        public string CorrectChoice { get; set; }
        [StringLength(12)]
        public string QuestionResult { get; set; }
    }
}
