// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("student_id", "quesiotn_id", "answer_date")]
[Table("student_answer_question")]
public partial class student_answer_question
{
    [Key]
    public int student_id { get; set; }

    public int? exam_id { get; set; }

    [Key]
    public int quesiotn_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string student_answer { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime answer_date { get; set; }

    [ForeignKey("exam_id")]
    [InverseProperty("student_answer_questions")]
    public virtual exam exam { get; set; }

    [ForeignKey("quesiotn_id")]
    [InverseProperty("student_answer_questions")]
    public virtual question quesiotn { get; set; }

    [ForeignKey("student_id")]
    [InverseProperty("student_answer_questions")]
    public virtual student student { get; set; }
}