// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("student")]
public partial class student
{
    [Key]
    public int student_id { get; set; }

    [ForeignKey("student_id")]
    [InverseProperty("student")]
    public virtual person studentNavigation { get; set; }

    [InverseProperty("student")]
    public virtual ICollection<student_answer_question> student_answer_questions { get; set; } = new List<student_answer_question>();

    [InverseProperty("student")]
    public virtual ICollection<student_course> student_courses { get; set; } = new List<student_course>();

    [InverseProperty("student")]
    public virtual ICollection<student_exam> student_exams { get; set; } = new List<student_exam>();
}