// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("student_id", "exam_id")]
[Table("student_exam")]
public partial class student_exam
{
    [Key]
    public int student_id { get; set; }

    [Key]
    public int exam_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string state { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? exam_date { get; set; }

    public int? grade { get; set; }

    [ForeignKey("exam_id")]
    [InverseProperty("student_exams")]
    public virtual exam exam { get; set; }

    [ForeignKey("student_id")]
    [InverseProperty("student_exams")]
    public virtual student student { get; set; }
}