// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[PrimaryKey("student_id", "course_id")]
[Table("student_course")]
public partial class student_course
{
    [Key]
    public int student_id { get; set; }

    [Key]
    public int course_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? enrollment_date { get; set; }

    [ForeignKey("course_id")]
    [InverseProperty("student_courses")]
    public virtual course course { get; set; }

    [ForeignKey("student_id")]
    [InverseProperty("student_courses")]
    public virtual student student { get; set; }
}