// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_system.Models;

[Table("topic")]
public partial class topic
{
    [Key]
    public int topic_id { get; set; }

    public int? topic_order { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string topic_duration { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string topic_title { get; set; }

    [InverseProperty("topic")]
    public virtual ICollection<course_questions_on_topic> course_questions_on_topics { get; set; } = new List<course_questions_on_topic>();
}